[package]
name = "cognexus-inspect"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }

common = { workspace = true }
