[package]
name = "cognexus-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }


cognexus-model = { workspace = true }
common = { workspace = true }
