[package]
name = "cognexus-model"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true }
thiserror = { workspace = true }
web-sys = { workspace = true }

common = { workspace = true }
